### ISSUE TITLE
saveWorld Command not working

### ISSUE THREAD

**Issue by darbdarb** [New-Project-Final-Final-WIP/HeadlessTweaks#11]
Steps:
1. Send Message to headless "/saveWorld".
2. Headless replies "Error: Exception has been thrown by the target of an invocation."

Possibly due to some updates?

**Comment by badhaloninja** [comment]
I found the problem, `QuantityX` was renamed to `Elements.Quantity`
However in the windows build (both headless and non headless) both still include the old `QuantityX` alongside the new `Elements.Quantity` so it wasn't immediately obvious what the problem was
