### ISSUE TITLE
Add thread_id to SendEmbed

### ISSUE THREAD

**Issue by Atakku** [New-Project-Final-Final-WIP/HeadlessTweaks#13]
Very simple fix, add a thread_id config option and pass it directly through to DIscord.Net's SendMessageAsync (its nullable, so you can just pass it as null if its null in config)

I want to move my webhook channel into a forum thread and this would help a lot

**Comment by badhaloninja** [comment]
Added in [v2.1.2](https://github.com/New-Project-Final-Final-WIP/HeadlessTweaks/releases/tag/v2.1.2)
