### ISSUE TITLE
Config JSON resets each launch

### ISSUE THREAD

**Issue by Ryn-Fox** [New-Project-Final-Final-WIP/HeadlessTweaks#15]
Each time I launch my headless with the mod, the rml_config/HeadlessTweaks.json resets to the following:
{
  "version": "1.0.0",
  "values": {
    "_configSaved": true
  }
}

Any idea what's going on?

**Comment by badhaloninja** [comment]
Are you perhaps editing the config file manually while the headless is running?

**Comment by Ryn-Fox** [comment]
To be absolutely sure, I've shutdown the headless, deleted the json, started the headless, and shut it down again without touching the file. Upon testing a few times, I see that it generates a full template on the first launch, but upon shutting down it wipes it to what's in the first post here.

**Comment by badhaloninja** [comment]
Sorry for taking such a long time to reply, I thought I had done so already

- Is this still a problem?
- Was there anything in the logs?

**Comment by badhaloninja** [comment]
I am now able to replicate this behavior consistently, I wonder why I wasn't able to before

I've found the problem, ResoniteModLoader saves all configs without defaults on shutdown, I'm fairly certain this did not behave like this when I first wrote HeadlessTweaks in Neos

[ShutdownHook](https://github.com/neos-modding-group/NeosModLoader/blob/master/NeosModLoader/ModConfiguration.cs#L676)
[SaveInternal](https://github.com/resonite-modding-group/ResoniteModLoader/blob/30f4955bc77cb315a2ce0700dadc28966d86ed98/ResoniteModLoader/ModConfiguration.cs#L496)

I am able to fix this on my end in 2 different ways
- Remove `_configSaved` and have it always save with defaults on launch
  - If the config isn't touched before the headless shuts down then it will keep the defaults
  - However once any config value is changed it will wipe the defaults from the file on shutdown again
  
- Turn off autosaving and instead manually save with defaults anytime a config value is changed
  - I don't think any config option would be changing enough for that to be an issue but it still feels a little dirty
  
  
One more solution is to create an issue on the ResoniteModLoader github requesting for a way to mark a config to auto save with defaults, which I might do later

**Comment by badhaloninja** [comment]
I forgot to actually respond to this issue after v2.1.5
I ended up just removing the `_configSaved` field

If the config has not been touched it will be populated with the defaults
