### ISSUE TITLE
Not responding to any commands

### ISSUE THREAD

**Issue by sveken** [New-Project-Final-Final-WIP/HeadlessTweaks#16]
Hello, 
When we message the headless with any commands like /help, Nothing happens. 
I have reinstalled the mod using the latest build from march and still no change. 
[e80fd886ea44 - 2024.5.22.1274 - 2024-05-24 07_04_13.log](https://github.com/New-Project-Final-Final-WIP/HeadlessTweaks/files/15422691/e80fd886ea44.-.2024.5.22.1274.-.2024-05-24.07_04_13.log)

Have attached the log file showing the mod trying to load. 
This is the only mod on the headless. 

Thanks.

**Comment by badhaloninja** [comment]
Please update ResoniteModLoader, you are using version 2.5.1 and headless tweaks is trying to use something that does not exist in that version 

https://github.com/resonite-modding-group/ResoniteModLoader/releases/tag/2.6.0

**Comment by sveken** [comment]
Yup, simple as that. 

Thank you
