### ISSUE TITLE
ReflectionTypeLoadException on Windows Headless

### ISSUE THREAD

**Issue by zkxs** [New-Project-Final-Final-WIP/HeadlessTweaks#4]
[full log file](https://gist.github.com/zkxs/acc225bc4d1843402ac2b5b300c0aacd)

This is a brand new headless install with all default configs, and the only installed mod is HeadlessTweaks v1.2.0.

My reproduction steps:

1. Install Neos Headless on Windows
2. Install NeosModLoader and HeadlessTweaks
4. Unblock `NeosModLoaderHeadless.dll`, `0Harmony.dll`, and `HeadlessTweaks.dll` in the [Windows file properties](https://raw.githubusercontent.com/neos-modding-group/NeosModLoader/master/doc/img/windows_unblock.png)
5. Do the [evil symlink hack](https://github.com/Neos-Metaverse/NeosPublic/issues/2638#issuecomment-1065851315)
6. Run `Neos.exe -LoadAssembly "Libraries/NeosModLoaderHeadless.dll"`

**Now here's the haunted part:** I also installed HeadlessTweaks into my normal, head-having Windows install and it *didn't* throw a ReflectionTypeLoadException. So either .NET is just behaving strangely and differently for the Headless instance, or something in [these three lines](https://github.com/New-Project-Final-Final-WIP/HeadlessTweaks/blob/c75820ceba56bf986c4a37ce2419ecab8fa92abf/HeadlessTweaks/HeadlessTweaks.cs#L112-L114) is causing issues. But also it's crashing before it's even able to hit the ["Discord.NET library not found"](https://github.com/New-Project-Final-Final-WIP/HeadlessTweaks/blob/c75820ceba56bf986c4a37ce2419ecab8fa92abf/HeadlessTweaks/HeadlessTweaks.cs#L100) log, so I'm just confused.

**Comment by zkxs** [comment]
If NML was the culprit I'd expect it to have crashed when I ran it on Windows headed. But it actually worked fine. But I see what you're saying: it's not OnEngineInit() that's crashing, it's InitializeMod(). So there's something going on here I still don't understand. For some reason headed can handle this case, while headless can't.

**Windows Headed Log Snippet:**
```log
11:02:27 PM.100 (  0 FPS)    [DEBUG][NeosModLoader] calling OnEngineInit() for [HeadlessTweaks]
11:02:28 PM.317 (  0 FPS)    [INFO] [NeosModLoader/HeadlessTweaks] Discord.NET library not found
11:02:28 PM.317 (  0 FPS)    [WARN] [NeosModLoader/HeadlessTweaks] Headless Not Detected! Skipping headless specific modules
```

[full log because snippets are annoying](https://gist.github.com/zkxs/48e165edd4de466f343244e931c9d1d5)

**Comment by zkxs** [comment]
I'm thinking the move here is to make a test build of NML that pulls the NeosMod type out of an assembly attribute instead of a type scan. So you'd add something like `[assembly: NeosMod(typeof(HeadlessTweaks))]` to your AssemblyInfo.cs, and this would opt you out of the type scan.

**Comment by badhaloninja** [comment]
I don't know the reason why there's a difference between headless and headed, ~~might have something to do with why windows headless is more type sensitive than the other versions ~~ Just remembered I'm pretty sure this also happens to linux headless, but my test environment is broken currently

On windows headless the error is thrown before OnEngineInit() is called
```
[INFO] [NeosModLoader] Compatibility hash spoofing succeeded
[INFO] [NeosModLoader] loading assemblies from nml_mods
[DEBUG][NeosModLoader] load assembly HeadlessTweaks.dll
[ERROR][NeosModLoader] ReflectionTypeLoadException initializing mod from C:\Program Files (x86)\Steam\steamapps\common\NeosVR\Tools\HeadlessClient\nml_mods\HeadlessTweaks.dll:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at NeosModLoader.ModLoader.InitializeMod(AssemblyFile mod)
   at NeosModLoader.ModLoader.LoadMods(Harmony harmony)
```

**Comment by badhaloninja** [comment]
> I'm thinking the move here is to make a test build of NML that pulls the NeosMod type out of an assembly attribute instead of a type scan. So you'd add something like `[assembly: NeosMod(typeof(HeadlessTweaks))]` to your AssemblyInfo.cs, and this would opt you out of the type scan.

I found [this](https://stackoverflow.com/questions/7889228/how-to-prevent-reflectiontypeloadexception-when-calling-assembly-gettypes) earlier which seems a little gross but

**Comment by zkxs** [comment]
Oh that's terrible. I'm using it immediately.
