### ISSUE TITLE
Commands say no permission, when yes perms

### ISSUE THREAD

**Issue by Merith-TK** [New-Project-Final-Final-WIP/HeadlessTweaks#5]
![image](https://github.com/New-Project-Final-Final-WIP/HeadlessTweaks/assets/10422110/13d60b27-b91c-46e1-b920-a80c15a2327a)
```json
{
	"version": "1.0.0",
	"values": {
		"UseDiscordWebhook": false,
		"DiscordWebhookID": null,
		"DiscordWebhookKey": null,
		"DiscordWebhookUsername": null,
		"DiscordWebhookAvatar": null,
		"AutoInviteOptOut": [],
		"PermissionLevels": {
			"Merith.TK": "Owner",
		},
		"WorldRoster": {},
		"SessionIdToName": {},
		"DefaultSessionAccessLevel": "FriendsOfFriends",
		"DefaultSessionHidden": true,
		"AlternateListAlpha": 0.7,
		"SmartAutosave": false,
		"_configSaved": true
	}
}
```

**Comment by badhaloninja** [comment]
It's looking for your user id no your user name, try "U-MerithTK"

**Comment by Merith-TK** [comment]
maybe add some kind of "check" to sanitize if needed in later versions?

**Comment by badhaloninja** [comment]
Well there is also the [/setPerm](https://github.com/New-Project-Final-Final-WIP/HeadlessTweaks#usage) command which I think does check iirc and I think I set it up so it can be used in the console, I'd have to check that though

**Comment by badhaloninja** [comment]
But yeah, I probably should make it sanitize the config at some point
